---
title: "Estimating amounts"
format:
  docx:
    toc: true
    number-sections: true
    reference_docx: template.docx
execute:
  echo: false
  message: false
  warning: false
---

```{r, setup}
#| echo: false

library(tidyverse)
library(gt)

#' First, run:
#' - 'R/install_and_setup.R'
#' - 'R/make_pops_from_propensity.R'
#' - 'R/run_euromod_runs.R'

run <- tar_read(run_models)

# Read in labels
statistics_page <- xml2::read_xml("UKMOD-PUBLIC-B2025.07/Statistics Presenter/UKMOD_1default.xml") 
  
labels_table <- xml2::xml_children(statistics_page)[3] |> 
  xml2::xml_child() |> 
  xml2::xml_child(6) |> 
  xml2::xml_child(1) |> 
  xml2::xml_find_all("Rows") |> 
  xml2::xml_children() |> 
  xml2::as_list() |> 
  purrr::map_dfr(\(Row) {
    
    tibble::tibble(
      variable = Row$CellAction$Parameters$Parameter$VarName[[1]],
      label = Row$Name[[1]]
    )
    
  }) |> 
  mutate(order = row_number()) |> 
  bind_rows(
    tribble(~variable, ~label,
            "bchmt_s", "Scottish Child Payment (including bridging, from 2020)",
            "ils_sicdy",	"...... national insurance contributions (personal)",
            "ils_sicer",	"...... National insurance contributions (employer)"
            )
  )

means_tested_bens <- c(
  "bsauc_s",
  "brduc_s",
  "bunmt_s",
  "bsa_s",
  "bsadi_s",
  "boamt_s",
  "boaht_s",
  "bmu_s",
  "bho_s",
  "brd_s",
  "bwkmt_s",
  "bfamt_s",
  "bmamt_s",
  "bmamt01_s",
  "bmascmt_s",
  "bch_s",
  "bchmt_s",
  "bchmt01_s",
  "bmascmt01_s",
  "bched01_s",
  "bched02_s",
  "bhosc01_s",
  "bsaec_s"
)

non_means_tested_bens <- c(
  "bmact_s",
  "bmanc_s",
  "bpact_s",
  "bunct_s",
  "bchht_s",
  "bcrdicm_s",
  "bwkmcee_s",
  "bwkmcse_s",
  "bedes",
  "bedsl",
  "bdioa",
  "bdisc",
  "bdimb",
  "bdiscwa",
  "bdimbwa",
  "bdict01",
  "bdict02",
  "bdiwi",
  "bcrdi",
  "bdisv",
  "bhlwk",
  "buntr",
  "bot")

non_means_pension <- c("boact_s", "boactcm", "boawr", "bsuwd")



direct_taxes <- c(
  "tin12_s",
  "tin11_s",
  "tin00_s",
  "i_bmu_tmu"
)

ni_contributions <- c(
  "ils_sicdy",
  "ils_sicer"
)

```

```{r calculating-amounts-by-year}

snapshot_amounts <- function(data, year) {
  
  all_totals <- data |>
    select(starts_with("b"), starts_with("i"), starts_with("ti"), dwt, -starts_with("id")) |> 
    # select(any_of(labels_table$variable), dwt) |> 
  summarise(across(everything(), ~sum(.x * dwt, na.rm = TRUE) * 12)) |> 
  pivot_longer(everything(), names_to = "variable", values_to = "gbp") |> 
  left_join(labels_table, by = "variable") |> 
  mutate(Benefit = label, Amount = scales::label_currency(prefix = "£")(gbp)) |> 
  mutate(gbp = if_else(str_detect(Benefit, "\\(-\\)"), -gbp, gbp)) |> 
  arrange(order) |> 
  replace_na(list(gbp = 0))

means_tot <- all_totals |> 
  filter(variable %in% means_tested_bens) |> 
  summarise(Expenditure__Means_tested_benefits = sum(gbp)) 

non_means_tot <- all_totals |> 
  filter(variable %in% non_means_tested_bens) |> 
  summarise(Expenditure__Non_means_tested_benefits = sum(gbp)) 

pension_out_tot <- all_totals |> 
  filter(variable %in% non_means_pension) |> 
  summarise(Expenditure__pensions  = sum(gbp)) 

direct_taxes_tot <- all_totals |> 
  filter(variable %in% direct_taxes) |> 
  summarise(Revenue__Direct_taxes = sum(gbp))

ni_contributions_tot <- all_totals |> 
  filter(variable %in% ni_contributions) |> 
  summarise(Revenue__NI_contributions = sum(gbp)) 


bind_cols(
  tibble(Year = year),
  means_tot,
  non_means_tot,
  pension_out_tot,
  direct_taxes_tot,
  ni_contributions_tot
) |> 
  pivot_longer(-Year, names_to = "calc", values_to = "gbp") |> 
  mutate(Amount = scales::label_currency(prefix = "£")(gbp))

  
}

format_gbp <- function(amt) {
  scales::label_currency(prefix = "£", suffix = "m")(amt / 1000000)
}

add_currency <- function(amt) {
  
  str_remove_all(amt, "[^\\d]") |>
    as.numeric() |>  
    sum() |> 
    format_gbp()
  
}

diff_currency <- function(amt, sign = "") {
  amt |>
    str_replace("m", ",000,000") |>
    str_remove_all("[^\\d]") |>
    as.numeric() |>
    diff() |>
    format_gbp() |> 
    paste0(sign, x = _)
  
}


read_in_pop <- function(dirname, label) {
  dir(file.path("output", dirname), full.names = TRUE) |>
    map(\(filename) {
      list(
        year = str_extract(filename, "\\d{4,4}"),
        data = data.table::fread(filename, sep = "\t", data.table = FALSE) |> as_tibble()
      )
    }) |>
    map( ~ snapshot_amounts(.x[[2]], .x[[1]])) |>
    reduce(bind_rows) |>
    mutate(comparison = label)
}

formatted_table <- function(comparison_data) {
  bind_rows(baseline_amounts_calc, comparison_data) |>
    separate_wider_delim(calc, delim = "__", names = c("cat", "source")) |>
    summarise(gbp = sum(gbp), .by = c(Year, cat, comparison)) |>
    pivot_wider(names_from = cat, values_from = gbp) |>
    gt(groupname_col = "Year", rowname_col = "comparison") |>
    fmt_currency(currency = currency(default = "£"), suffixing =  c(NA, "M", NA, NA)) |>
  tab_options(
    summary_row.background.color = "lightgrey",
    grand_summary_row.background.color = "lightgrey"
  ) |>
    summary_rows(
      fns = list(label = "Annual difference", fn = "diff"),
      fmt = ~ fmt_currency(
        .x,
        currency = currency(default = "£"),
        suffixing =  c(NA, "M", NA, NA)
      )
    ) |> 
   tab_style(
  style = cell_text(weight = "bold"),
  locations = list(cells_summary())
)
}

```

```{r read-in-numbers-employed}

matched_pop_in <- dir("data", pattern = "matching_updated_pop.*") |> 
  set_names() |> 
  map(~read_tsv(file.path("data", .x), col_select = c("enter_employment", "dwt")))

n_workers <- matched_pop_in |> 
  map(\(dt) {
    summarise(dt, n_entering_employment = sum(enter_employment * dwt, na.rm = TRUE))
  }) |> 
  imap_dfr(~tibble(filename = .y, n_workers = .x$n_entering_employment)) |> 
  inner_join(
    tribble(~filename, ~comparison,
            "matching_updated_pop_seeking_u25_5pc.txt", "Under-25s - 5% increase",
            "matching_updated_pop_sick_or_disabled_u25_5pc.txt", "Under-25s, sick or disabled - 5% increase",
            "matching_updated_pop_seeking_o25_5pc.txt", "Aged 25-64 - 5% increase",
            "matching_updated_pop_sick_or_disabled_o25_5pc.txt", "Aged 25-64, sick or disabled - 5% increase",
    )
  ) |> 
  select(comparison, n_workers)

```


# Estimating baseline amounts

```{r baseline-estimates}

baselines <- dir("output/baseline", full.names = TRUE) |> 
  map(\(filename) {
    list(
      year = str_extract(filename, "\\d+"),
      data = data.table::fread(filename, sep = "\t", data.table = FALSE) |> as_tibble()
    )
  })

baseline_amounts_calc <- baselines |> 
  map(~snapshot_amounts(.x[[2]], .x[[1]])) |> 
  reduce(bind_rows) |> 
  mutate(comparison = "Baseline")

baseline_amounts_calc |> 
  # mutate(Amount = format_gbp(gbp)) |> 
  mutate(Amount = gbp) |> 
  select(-gbp, -comparison) |> 
  pivot_wider(names_from = Year, values_from = Amount) |> 
  separate_wider_delim(calc, delim = "__", names = c("cat", "source")) |>  
  mutate(source = str_replace_all(source, "_", " ")) |> 
  gt(rowname_col = "source", groupname_col = "cat") |> 
  fmt_currency(currency = currency(default = "£"), suffixing = TRUE) |> 
    tab_options(
    summary_row.background.color = "lightgrey",
    grand_summary_row.background.color = "lightgrey"
  ) |>
  summary_rows(
    # cols = `2026`:`2029`,
    fns = list(
      label = "Total",
      fn = "sum"
    ),
    fmt = ~fmt_currency(.x, currency = currency(default = "£"), suffixing = c(NA, "M", NA, NA))
  ) |> 
  grand_summary_rows(
    fns = list(
      label = "Total in - out") ~-diff(.x),
    fmt = ~fmt_currency(.x, currency = currency(default = "£"), suffixing = c(NA, "M", NA, NA))
  ) |> 
   tab_style(
  style = cell_text(weight = "bold"),
  locations = list(cells_summary(), cells_grand_summary())
)
  
```

# Under 25 and seeking work


```{r under-25-seeking}

under_25_seeking <- read_in_pop("uprated_seeking_u25_5pc", "Under-25s - 5% increase") 

under_25_seeking |> 
  formatted_table()

```

# Under 25 and sick or disabled

```{r under-25-dlltsd}

under_25_sick_or_disabled <- read_in_pop("uprated_sick_or_disabled_u25_5pc", "Under-25s, sick or disabled - 5% increase") 

under_25_sick_or_disabled |> 
  formatted_table()

```

# 25 or over and seeking work

```{r over-25-seeking}

over_25_seeking <- read_in_pop("uprated_seeking_o25_5pc", "Aged 25-64 - 5% increase") 

over_25_seeking |> 
  formatted_table()

```

# 25 or over and sick or disabled

```{r over-25-dlltsd}

over_25_sick_or_disabled <- read_in_pop("uprated_sick_or_disabled_o25_5pc", "Aged 25-64, sick or disabled - 5% increase") 
over_25_sick_or_disabled |> 
  formatted_table()

```

# All years combined

```{r all-years}

total_cals <- bind_rows(
  under_25_seeking,
  under_25_sick_or_disabled,
  over_25_seeking,
  over_25_sick_or_disabled
) |> 
  left_join(baseline_amounts_calc |>
              select(Year, calc, gbp_base = gbp), by = join_by(Year, calc)) |> 
  mutate(difference = gbp - gbp_base) |> 
  separate_wider_delim(calc, delim = "__", names = c("direction", "cat")) |> 
  summarise(difference = sum(difference), .by = c("Year", "direction", "comparison")) |> 
  pivot_wider(names_from = c("direction"), values_from = difference) |> 
  mutate(Total = Revenue - Expenditure) |> 
  left_join(n_workers)

total_cals |> 
  pivot_wider(names_from = Year, values_from = c(Expenditure, Revenue, Total)) |> 
  select(comparison, ends_with("2026"),
         ends_with("2027"),
         ends_with("2028"),
         ends_with("2029")) |> 
  gt(rowname_col = "comparison") |> 
  tab_spanner_delim("_", reverse = TRUE) |> 
  fmt_currency(currency = currency(default = "£"), decimals = 0, suffixing =  c(NA, "M", NA, NA)) |> 
   tab_style(
  style = cell_text(weight = "bold"),
  locations = cells_body(
  columns =  starts_with("Total")
  )
)

```

Increased income per person:

```{r}
total_cals |> 
  select(Year, comparison, Total, `Persons entering work` = n_workers) |> 
  mutate(`Change per person` = Total/`Persons entering work`) |> 
  pivot_wider(names_from = Year, values_from = c(Total, `Change per person`),
              id_cols = c(`Persons entering work`, comparison)) |> 
  select(comparison, ends_with("2026"),
         ends_with("2027"),
         ends_with("2028"),
         ends_with("2029")) |> 
  gt(rowname_col = "comparison") |> 
  tab_spanner_delim("_", reverse = TRUE) |> 
  fmt_currency(currency = currency(default = "£"), decimals = 0, suffixing =  c(NA, "M", NA, NA))
  
```


## Totals

```{r}
total_cals |> 
  summarise(
    `Total savings` = sum(Total),
    .by = comparison) |> 
  gt(rowname_col = "comparison")  |> 
  fmt_currency(currency = currency(default = "£"), decimals = 0, suffixing =  c(NA, "M", NA, NA))  |>
  grand_summary_rows(
    fns = list(
      label = "Total",
      fn = "sum"
    ),
    fmt = ~fmt_currency(.x, currency = currency(default = "£"), suffixing = c(NA, "M", NA, NA))
  ) |> 
   tab_style(
  style = cell_text(weight = "bold"),
  locations = list(cells_grand_summary())
)
  
```


```{r graphing-pop-differences}

total_cals |> 
  pivot_longer(Expenditure:Revenue, names_to = "dir", values_to = "gbp") |> 
  mutate(gbp = if_else(dir == "Expenditure", -gbp, gbp),
         comparison = fct_inorder(comparison),
         Year = fct_rev(Year)) |> 
  ggplot(aes(gbp, Year, fill = dir)) +
  geom_col(position = "stack") +
  facet_wrap(~comparison, ncol = 1) + 
  theme_minimal() + 
  MetBrewer::scale_fill_met_d(name = "Benefits savings/\nTax income increase",
                              palette_name = "Austria",
                              labels = c("Benefits expenditure", "Tax Revenue")) +
  xlab("£ saving") +
  scale_x_continuous(labels = scales::label_currency(prefix = "£"))
  
```

# Estimating costs

```{r}


costs_per_person <- tribble(
  ~age_group, ~employment_status, ~cost,
  "Under-25", "Unemployed, looking for work", 8369,
  "Under-25", "Sick or disabled", 8369,
  "25-64", "Unemployed, looking for work", 8369,
  "25-64", "Sick or disabled", 8369,
)

costs_per_person <- tribble(~cost, ~comparison,
        8369, "Under-25s - 5% increase",
        8369, "Under-25s, sick or disabled - 5% increase",
        8369, "Aged 25-64 - 5% increase",
        8369, "Aged 25-64, sick or disabled - 5% increase",
)

n_workers |>
  left_join(costs_per_person) |>
  mutate(`Total cost of program` = n_workers * cost, n_workers = round(n_workers)) |>
  left_join(total_cals |>
              summarise(`Total savings` = sum(Total), .by = comparison)) |> 
  select(comparison, `Number of people returning to work` = n_workers, `Cost per person` = cost,
         `Total cost of program`, `Total savings`) |> 
  gt(rowname_col = "comparison") |> 
  fmt_currency(currency = currency(default = "£"), decimals = 0, suffixing =  c(NA, "M", NA, NA), columns = -`Number of people returning to work`)  |> 
  fmt_number(columns = `Number of people returning to work`, decimals = FALSE)
  

```


